### ISSUE TITLE
Сервис мониторинга каталога(Оператор сканирования)-Асинхронный

### ISSUE THREAD

**Issue by Dmitry-Ischenko** [GeekBrains-Internship-2022/Scanner#2]
Входные данные:
-путь к каталогу отсканированых документов
Алгоритм:
-Отселижвание появление новых файлов в каталоге мониторинга
фильтр файлы *.pdf
уровень вложености 1
создание файла
- передача пути к файлу подписавшимся через событие

**Comment by kpuk77** [comment]
~~Сделано! По готовности логера, необходимо будет внести изменения.~~
В работе..
